### PR TITLE
Tiagogomes/unit test fixes

### PR DESCRIPTION
**Pull request by tacgomes**

### CODE REVIEW

**Comment by leeming** [comment]
Does not pass some tests due to python 2->3

```
        pipe_parent, pipe_child = multiprocessing.Pipe()

        with mount_all(filesystem_root, extra_mounts):

            # Awful hack to ensure string-escape is loaded:
            #
            # this ensures that when propagating an exception back from
            # the child process in a chroot, the required string-escape
            # python module is already in memory and no attempt to
            # lazy load it in the chroot is made.
>           unused = "Some Text".encode('string-escape')
E           LookupError: unknown encoding: string-escape

.tox/py34/lib/python3.4/site-packages/sandboxlib/chroot.py:234: LookupError

```

The following seems to work, but not 100% if functionally equivalent 
`"Some Text".encode('unicode-escape')`

**Comment by tacgomes** [comment]
@ssssam I tried to reproduce the problem by not lazy-loading string-escape (or unicode-escape). However, the exception was always propagated correctly. I'll do your suggestion to avoid possible regressions in other distros/machines.

**Comment by leeming** [comment]
All looks great. One bug minor of tab/space indent

[test_all.py#164](https://github.com/CodethinkLabs/sandboxlib/blob/5501382f7dfa57026c79710881e6cd0d5be8aff3/tests/test_all.py#L164) fails to run for me due to tab char instead of spaces (silly python)

> E     File "/home/andrewleeming/baserock/sandboxlib/tests/test_all.py", line 164
> E       with pytest.raises(AssertionError) as excinfo:
> E                                                    ^
> E   TabError: inconsistent use of tabs and spaces in indentation

I fixed that, but then getting

> tests/test_all.py:123: in <module>
>     class TestMounts(object):
> tests/test_all.py:165: in TestMounts
>     exit, out, err = sandboxlib_executor.run_sandbox(
> E   AttributeError: 'function' object has no attribute 'run_sandbox'

**Comment by tacgomes** [comment]
@leeming can you pull again and have another try please?

**Pull request merged**
